# Generated by Django 6.1 on 2026-10-09 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('executing', 'executing'), ('completed', 'completed'), ('partially_completed', 'partially_completed'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('rolled_back', 'rolled_back')], default='planned', max_length=24)),
                ('total_items', models.IntegerField(default=0)),
                ('successful_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_operation',
            },
        ),
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.IntegerField()),
                ('source_path', models.CharField(max_length=1024)),
                ('target_path', models.CharField(max_length=1024)),
                ('action', models.CharField(choices=[('move', 'move'), ('copy', 'copy'), ('quarantine', 'quarantine'), ('delete', 'delete')], default='move', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped'), ('conflict', 'conflict')], default='pending', max_length=16)),
                ('pre_state', models.JSONField(default=dict)),
                ('post_state', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.operation')),
            ],
            options={
                'db_table': 'operations_operationitem',
                'ordering': ['item_index'],
            },
        ),
    ]
