# Generated by Django 6.1 on 2026-10-09 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_category',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=1024)),
                ('canonical_path', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=256)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('is_directory', models.BooleanField(default=False)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mtime_ns', models.BigIntegerField(blank=True, null=True)),
                ('ctime_ns', models.BigIntegerField(blank=True, null=True)),
                ('inode_identity', models.CharField(blank=True, max_length=64)),
                ('is_symlink', models.BooleanField(default=False)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('partial_hash', models.CharField(blank=True, max_length=64)),
                ('hash_stage', models.CharField(choices=[('none', 'none'), ('partial', 'partial'), ('full', 'full'), ('error', 'error')], default='none', max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='catalog.category')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder')),
            ],
            options={
                'db_table': 'catalog_file',
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='catalog.file')),
            ],
            options={
                'db_table': 'catalog_filemetadata',
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['folder', 'canonical_path'], name='catalog_fil_folder__656f06_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['extension'], name='catalog_fil_extensi_41a2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['category'], name='catalog_fil_categor_254a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha256'], name='catalog_fil_sha256_92b1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['deleted_at'], name='catalog_fil_deleted_3c7d3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('folder', 'relative_path'), name='unique_file_path_active'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='file_size_non_negative'),
        ),
    ]
