# Generated by Django 6.1 on 2026-10-09 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('recursive', models.BooleanField(default=True)),
                ('follow_symlinks', models.BooleanField(default=False)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folders_folder',
                'indexes': [models.Index(fields=['user', 'path'], name='folders_fol_user_id_295ee4_idx'), models.Index(fields=['is_active', 'is_watched'], name='folders_fol_is_acti_9eea36_idx')],
            },
        ),
    ]
