# Generated by Django 6.1 on 2026-10-09 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_action', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('dismissed', 'dismissed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='catalog.file')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='rules.organizationrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestions_organization_suggestion',
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='suggestion_confidence_range')],
            },
        ),
    ]
