# Generated by Django 6.1 on 2026-10-09 09:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('member_count', models.IntegerField(default=0)),
                ('reclaimable_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'duplicates_duplicategroup',
            },
        ),
        migrations.CreateModel(
            name='DuplicateMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_keeper', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_memberships', to='catalog.file')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='duplicates.duplicategroup')),
            ],
            options={
                'db_table': 'duplicates_duplicatemember',
                'constraints': [models.UniqueConstraint(fields=('group', 'file'), name='unique_group_file_member')],
            },
        ),
    ]
